// @ts-check

/**
 * automatically generated by `vivth.JSautoDOC`
 * @copyright
 * this library is made and distributed under MIT license;
 */

export { Xixth } from './src/Xixth.mjs';
/**
 * @typedef {import('./src/FlagEntry.mjs').FlagEntry} FlagEntry
 */