// @ts-check

/**
 * automatically generated by `vivth.JSautoDOC`
 * @copyright
 * this library is made and distributed under MIT license;
 */

export { AddBin } from './src/AddBin.mjs';
export { Xixth } from './src/Xixth.mjs';
/**
 * @typedef {import('./src/AddBinRegisterReferenceOptions.mjs').AddBinRegisterReferenceOptions} AddBinRegisterReferenceOptions
 */
/**
 * @typedef {import('./src/FlagEntry.mjs').FlagEntry} FlagEntry
 */
/**
 * @typedef {import('./src/HandleOnCopyHandler.mjs').HandleOnCopyHandler} HandleOnCopyHandler
 */
/**
 * @typedef {import('./src/PathCopyHandler.mjs').PathCopyHandler} PathCopyHandler
 */